### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by davidrhyswhite** [tjdavies/copal#1]
I cant seem to comment on Slack from their airport so I thought I'd note my queries down...
- When you say `thisless`, do we use the `this` keyword a lot in the current Redux implementation? I can't think of places in Redux it's used.
- How about loading asynchronous data?
- How about passing actions to components further down the stack? The example is very simple, however a real application will likely need a lot more passed down. Redux solves this with `bindActionCreators` and the `connect` methods... How would this library solve that?
- Following on from the previous questions, what is responsible for loading the data? The example shows that the `App` is, however that is going to make that component responsible for far more than it should be concerned with...
- Routing... Are we still able to use the react-router?

It'd be nice to see an example closer to our current application.

It looks good otherwise, my only initial concern would be around loading data from multiple sources, and our dependencies that are built upon Redux. We would need to continuously ensure that this library was inline and working with our Redux specific dependencies if and when those update.

**Comment by tjdavies** [comment]
So firstly I'm not sure we should replace Redux in our apps it may be to far gone for that. This is more a personal project to change things more to my liking. I suspect others have the same misgivings.  However to answer your questions.
- we use `this` in containers. Containers are not strictly a requirement of Redux however it is the method used in most examples. 
- async is one prime reasons for wanting to change redux. This way is much more natural. I'll provide an example when I have a sec.
- connect isn't strictly part of the core redux. I dislike this for many reasons. Mainly because it spoils the functional purity of `render(state)` => `vdom.` Also it binds your actions into react. If you wanted to move to say virtual dom you would have trouble. In the example rendering and application logic are separated. Passing the data down the tree is in my opinion less of an overhead than additional container objects. It is clean and honest.
- actions are responsible for loading the data again I need to provide an example. But the view(react) is only concerned with rendering. Here is a simple example of showing a page and triggering a call to load data. I find this concise and easy to reason about as its all in one place

```
showPageAction() {
    showLoadingPage();
    loadData().then(
       showPageWithData
    );
 }
```
- routing I dislike the react router. It seems odd for the view to drive the app. I would suggest using something like  [Page.js](https://visionmedia.github.io/page.js/) and wire routes up to actions like the above. That way its treated consistently with any other form of user input.

Thanks for this though I appreciate the time and thought. It shows I need to add more examples to show how I would see these concerns addressed.

**Comment by tjdavies** [comment]
added async example to match the redux one
